
[pytest]
addopts =
    --import-mode=importlib
    --showlocals
    -v
    -ra
    --durations=10
    --junit-xml=reports/junit.xml
    --html=reports/report.html
    --self-contained-html
    --report-log=reports/reportlog.jsonl


junit_logging = all
junit_log_passing_tests = True

junit_suite_name = SystemX

log_level = DEBUG
log_format = %(asctime)s.%(msecs)03d [%(levelname).1s] %(message)s [%(name)s]
log_date_format = %m-%d %H:%M:%S

log_file_format = %(asctime)s.%(msecs)03d [%(levelname).1s] %(message)s [%(name)s]
log_file_date_format = %m-%d %H:%M:%S